name: "Build check gemstone in SDK"
run-name: SDK build check to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: [push, pull_request]
jobs:
  build-check-sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup SDK
      run: docker pull servostar/gemstone:sdk-"$SDK"
    - name: Compile
      run: run-check-test.sh
